use ecommers ;

--         Reusable View

CREATE OR REPLACE VIEW vw_sales AS
SELECT
    transaction_id,
    customer_id,
    age,
    gender,
    product_name,
    product_category,
    payment_mode,
    status,
    order_date,
    order_time,
    quantity,
    price,
    total_price,
    total_cost,
    (total_price - total_cost) AS profit
FROM sales_clean;

--      Indexes
CREATE INDEX idx_customer ON sales_clean(customer_id);
CREATE INDEX idx_product ON sales_clean(product_name);
CREATE INDEX idx_category ON sales_clean(product_category);
CREATE INDEX idx_order_date ON sales_clean(order_date);
CREATE INDEX idx_payment ON sales_clean(payment_mode);
CREATE INDEX idx_status ON sales_clean(status);

SHOW indexes FROM sales_clean ;

--                     Sales Analysis (Business Questions)

--              1.Sales Analysis
-- What is the total revenue generated by the business?
SELECT ROUND(SUM(total_price),2) AS total_revenue FROM vw_sales;

-- How many orders were completed?
SELECT COUNT(transaction_id) AS total_orders FROM vw_sales;

-- What is the average order value?
 SELECT ROUND(AVG(total_price),2) AS avg_order_value FROM vw_sales;

-- Which month generated the highest sales?
SELECT
    MONTHNAME(order_date) AS month_name,
    FORMAT(SUM(total_price),0) AS highest_sales
FROM vw_sales
GROUP BY MONTHNAME(order_date)
ORDER BY highest_sales DESC
LIMIT 1;

-- Which day of the week has the highest sales?
WITH day_sales AS (
SELECT DAYNAME(order_date ) as day_name ,
      SUM(total_price) AS total_sales ,
      ROW_NUMBER() OVER(  ORDER BY SUM(total_price) DESC)as rnk  
      FROM vw_sales
      GROUP BY  DAYNAME(order_date )
 )
SELECT day_name ,  FORMAT((total_sales),0) AS highest_sales 
FROM day_sales
WHERE rnk = 1 ;

-- What are the sales trends over time?
SELECT
CASE
    WHEN time_of_purchase BETWEEN '00:00:00' AND '02:59:59' THEN '00-03'
    WHEN time_of_purchase BETWEEN '03:00:00' AND '05:59:59' THEN '03-06'
    WHEN time_of_purchase BETWEEN '06:00:00' AND '08:59:59' THEN '06-09'
    WHEN time_of_purchase BETWEEN '09:00:00' AND '11:59:59' THEN '09-12'
    ELSE '12+'
END AS sales_period,
FORMAT(SUM(total_price),0) AS total_sales
FROM vw_sales
GROUP BY sales_period
ORDER BY total_sales DESC;

--               2.Customer Analysis

-- Average Spend per Customer
SELECT customer_id , FORMAT(AVG(total_price),2) AS Avg_Spend_per_Customer
FROM vw_sales 
GROUP BY customer_id
ORDER BY Avg_Spend_per_Customer DESC ;

-- Customers with the Most Orders
SELECT 
	customer_id ,
    COUNT(*) AS most_orders
FROM vw_sales 
GROUP BY customer_id
ORDER BY most_orders DESC
LIMIT 5 ;

-- Customer Lifetime Value (CLV)
SELECT 
	customer_id ,
    COUNT(*) as total_orders,
    FORMAT(SUM(total_price),2) AS customer_lifetime_value
FROM vw_sales 
GROUP BY customer_id 
ORDER BY customer_lifetime_value DESC ;

-- How many unique customers do we have?
SELECT COUNT(DISTINCT customer_id ) AS unique_customers FROM vw_sales ;

-- Who are the top 10 customers by total spending?
SELECT
    customer_id,
    COUNT(*) AS total_orders,
    FORMAT(SUM(total_price),0) AS total_spending
FROM vw_sales
GROUP BY customer_id
ORDER BY total_spending DESC
LIMIT 10;

-- Which age group contributes the most revenue?
SELECT CASE 
		WHEN age BETWEEN 18 AND 24 THEN '18 to 24'
        WHEN age BETWEEN 25 AND  30 THEN '25 to 30'
        WHEN age BETWEEN 31 AND 40 THEN '31 to 40'
        WHEN age BETWEEN 41 AND  50 THEN '41 to 50'
        ELSE '51+'
        END AS age_group ,
        FORMAT(SUM(total_price),0) AS total_revenue
from vw_sales 
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Do male or female customers spend more?
SELECT gender ,  FORMAT(SUM(total_price),0) AS total_spend FROM  vw_sales 
GROUP BY gender
ORDER BY total_spend DESC;

-- How many repeat customers do we have?
WITH frequency_customers AS(
		SELECT customer_id  ,
               COUNT(transaction_id) AS total_orders
        FROM vw_sales
        GROUP BY customer_id 
        HAVING COUNT(transaction_id) > 1
) SELECT  COUNT(*) as  repeat_customers FROM frequency_customers  ;

--             3.Product Analysis

-- Top 5 Best Selling Products ?
SELECT
    product_name,
    SUM(quantity) AS total_quantity_sold
FROM vw_sales
GROUP BY product_name
ORDER BY total_quantity_sold DESC
LIMIT 5;

-- Average Selling Price by Product ?
SELECT
    product_name,
    ROUND(AVG(price),2) AS avg_price
FROM vw_sales
GROUP BY product_name;

-- Highest Profit Product
SELECT
    product_name,
    FORMAT(SUM(total_price- total_cost),0) AS profit
FROM vw_sales
GROUP BY product_name
ORDER BY profit DESC;

-- Revenue Contribution %
SELECT
    product_name,
    CONCAT(
		FORMAT(
			SUM(total_price) * 100 / 
			(SELECT SUM(total_price) FROM sales) ,
		0) ,
	'%')AS revenue_percentage
FROM vw_sales
GROUP BY product_name
ORDER BY revenue_percentage DESC;

-- Which products generate the highest revenue?
SELECT 
	product_name , 
    FORMAT(SUM(total_price),0) AS highest_revenue
FROM  vw_sales 
GROUP BY product_name
ORDER BY highest_revenue DESC
LIMIT 5 ;

-- Which products have the highest sales quantity?
SELECT 
	product_name , 
    SUM(quantity) AS highest_sales_quantity
FROM  vw_sales 
GROUP BY product_name
ORDER BY highest_sales_quantity DESC
LIMIT 5 ;

-- Which product category performs the best?
SELECT 
	product_category , 
    SUM(quantity) AS highest_sales_quantity,
    FORMAT(SUM(total_price),0) AS highest_revenue 
FROM  vw_sales 
GROUP BY product_category
ORDER BY highest_revenue DESC
 LIMIT 1 ;
 
-- Which products should be discontinued due to poor sales?
SELECT 
	product_name, 
    SUM(quantity) AS highest_sales_quantity,
    FORMAT(SUM(total_price),0) AS highest_revenue 
FROM  vw_sales 
GROUP BY product_name
ORDER BY highest_revenue
 LIMIT 5 ;

--         4.Payment Analysis

-- Which payment method is used the most?
SELECT  
	payment_mode , 
	COUNT(transaction_id) as total_count 
FROM vw_sales
GROUP BY payment_mode 
ORDER BY total_count  DESC;
 
-- Which payment method generates the highest revenue?
SELECT  
	payment_mode , 
	FORMAT(SUM(total_price),0) as highest_revenue 
FROM vw_sales
GROUP BY payment_mode 
ORDER BY highest_revenue  DESC;

-- Average Order Value by Payment Method ?
SELECT  
	payment_mode , 
	ROUND(AVG(total_price),2) as Avg_Order_Value 
FROM vw_sales
GROUP BY payment_mode 
ORDER BY Avg_Order_Value  DESC;

-- Revenue Contribution by Payment Method ?
SELECT  
	payment_mode , 
	CONCAT(
		ROUND(
			SUM(total_price) * 100 / (SELECT SUM(total_price) FROM sales),
		0),
        '%')as Avg_Order_Value 
FROM vw_sales
GROUP BY payment_mode 
ORDER BY Avg_Order_Value  DESC;

-- Total Quantity Sold by Payment Method
SELECT  
	payment_mode , 
	ROUND(SUM(quantity),0) as Avg_Order_Value 
FROM vw_sales
GROUP BY payment_mode 
ORDER BY Avg_Order_Value  DESC;

--         5.Order Status
-- How many orders were completed, cancelled, returned, and pending?
SELECT
    status,
    COUNT(transaction_id) AS total_orders
FROM vw_sales
GROUP BY status
ORDER BY total_orders DESC;

-- What is the order cancellation rate , return rate ,delivered rate and pending rate?
SELECT 
	status , 
    COUNT(*) as total_orders ,
		CONCAT(
			FORMAT(
				COUNT(*)* 100 /( SELECT  COUNT(*)FROM sales ),
			0),
		'%')as order_status_percentage
FROM vw_sales 
GROUP BY status  ;

-- Revenue generated by each status ?
SELECT 
	status ,
    FORMAT(
		SUM(total_price) ,
        0) AS loss_of_Revenue 
FROM vw_sales 
GROUP BY status  ;

--         6.Profit Analysis
-- What is the total profit?
SELECT 
	FORMAT(SUM(total_price),0 ) AS total_sales ,
	FORMAT(SUM(total_price - total_cost),0 ) AS total_profit 
FROM vw_sales ;

-- Which product has the highest profit margin?
SELECT 
	product_name ,
	CONCAT(
		ROUND(
			SUM(total_price - total_cost) * 100 / SUM(total_price )
		,1 ),
	'%' )
	AS  profit_margin
FROM vw_sales
GROUP BY product_name 
ORDER BY  profit_margin DESC
LIMIT 1;

-- Which category is the most profitable?
SELECT 
	product_category ,
	CONCAT(
		ROUND(
			SUM(total_price - total_cost) * 100 / SUM(total_price )
		,1 ),
	'%' )
	AS profit_margin
FROM vw_sales
GROUP BY product_category 
ORDER BY  profit_margin DESC
LIMIT 1;















